runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: bot.py
branches:
  only:
  - master
install:
- pip install pyTelegramBotAPI
- pip install lxml
script:
- ./scripts/travis.sh
